language: go
go: "1.12.x"

script:
  - GO111MODULE=on go get -u github.com/urfave/cli
  - GO111MODULE=auto go get -u github.com/urfave/cli
  - GO111MODULE=off go get -u github.com/urfave/cli

notifications:
  email: false
